### ISSUE TITLE
What the purpose of AllowGlobalUpdate?

### ISSUE THREAD

**Issue by rts-gordon** [go-gorm/caches#17]
Hi @xpume 

 I noticed that there is a new config "AllowGlobalUpdate=true" in the latest examples, I test it but found no difference with old version. May I know what's the purpose of AllowGlobalUpdate? and when can we use it? Thank you.

**Comment by ktsivkov** [comment]
Hi @rts-gordon ,
It's referring to this: https://gorm.io/docs/session.html#AllowGlobalUpdate

**Comment by rts-gordon** [comment]
Hi @ktsivkov 

  Thanks for your reply, I read the docs and tested the new and old code, but found no difference. Can you please tell me how to build the test cases to show the difference? Thank you.

**Comment by xpume** [comment]
https://github.com/go-gorm/caches/blob/1b3e58f126151b57317c216804daf2018c0faed9/README.md?plain=1#L218-L236
`db.Delete()`return`WHERE conditions required`, it's a [gorm](https://github.com/go-gorm/gorm) config/issue, not [caches](https://github.com/go-gorm/caches) config/issue.

**Comment by rts-gordon** [comment]
Hi @xpume 
  Got it.  
  Use ```db.Delete(&UserModel{})```  and ```AllowGlobalUpdate=true``` will delete all user records, this is not safe;
  maybe use ```db.Delete(&UserModel{Id: 123})```  and ```AllowGlobalUpdate=false``` will be more safer.
