### ISSUE TITLE
How to chose use or don't use Redis cache via Context?

### ISSUE THREAD

**Issue by rts-gordon** [go-gorm/caches#18]
Hi there

@mgdigital From [issue 9](https://github.com/go-gorm/caches/issues/9), we know that the client can decide whether to use Redis cache. This is a great idea, just want to know how to use it?

If there are two models, model A wants to use Redis cache, model B do not. Both of them use the same Caches interface, how to use Context to impl this? Can you kindly give an example? 

Thank you.

**Comment by mgdigital** [comment]
Hi, you can use `context.WithValue` to pass any information, such as caching preferences, to the cache implementation: https://pkg.go.dev/context#WithValue

Although this is considered an anti-pattern it can achieve the desired effect here.

**Comment by rts-gordon** [comment]
Thanks @mgdigital , I learned a lot from those code.
