### ISSUE TITLE
Pass a context to the Cacher interface

### ISSUE THREAD

**Issue by mgdigital** [go-gorm/caches#9]
## Describe the feature

The `Cacher` interface would have an additional first argument of a `context.Context` obtained from the DB `Statement`.

## Motivation

- It would be idiomatic to pass a context to a blocking cache adapter such as Redis.
- I wish to explicitly mark queries as being cacheable. For this I am adding a value to the context object; queries without this value will be uncached. I appreciate this is a controversial pattern but it is the simplest way to achieve this without support within Gorm itself. This is perhaps a separate issue, but having the context argument at least provides a workaround.

I appreciate this is a breaking change. For now I have forked this library to add this argument to the `Cacher`. See https://github.com/mgdigital/gorm-cache/pull/1/files

**Comment by ktsivkov** [comment]
@mgdigital closed with https://github.com/go-gorm/caches/releases/tag/v3.0.0

**Comment by rts-gordon** [comment]
Hi @mgdigital 
  
  Add context to interface is a goo idea, I want to know how to use it? 

  If there are two models, model A wants to use Caches, model B do not. Both of them use the same Caches interface, so how to use context to impl this? Can you kindly give an example? Thank you.
